apiVersion: v1
kind: Service
metadata:
  name: personal-site-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 8080
      targetPort: 80

      # Note to self: This is optional and is normally
      # allocated by the control plane
      # nodePort: 30007
