apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site
  labels:
    app: frontend
  annotations:
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      hostNetwork: true
      containers:
      - name: personal-site-container
        image: wheresmycookie/personal-site:latest
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 30
        ports:
        - containerPort: 80
